driver:
  browser: firefox
  download_link: https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  untar_folder: .framler_firefox_driver
  untar_fname: geckodriver

site:
  dantri:
    title:
      name: "h1"
    authors:
      name: None
    text:
      class_: "detail-content"
    pubd:
      class_: "tt-capitalize"
    tags:
      class_: "news-tag-list"
    image_urls:
      class_: "image"

  vnexpress:
    title:
      class_: "title_news"
    authors:
      name: None
    text:
      class_: "fck_detail"
    pubd:
      class_: "block_timer"
    tags:
      class_: "tag_item"
    image_urls:
      class_: "tplCaption"

  vietnamnet:
    title:
      name: "h1"
      class_: "title"
    authors:
      name: None
    text:
      id: "ArticleContent"
      class_: "ArticleContent"
    pubd:
      class_: "ArticleDate"
    tags:
      id: "BoxTag"
    image_urls:
      class_: "ImageBox"

  tuoitrevn:
    title:
      name: "h1"
      class_: "article-title"
    authors:
      class_: "author"
    text:
      id: "main-detail-body"
    pubd:
      class_: "date-time"
    tags:
      class_: "tags-item"
    image_urls:
      class_: "detail-img-lightbox"

  thanhnien:
    title:
      name: "h1"
      class_: "details__headline"
    authors:
      class_: "details__author__meta"
    text:
      class_: "details__content"
    pubd:
      class_: "details__meta"
    tags:
      class_: "details__tags"
    image_urls:
      name: "a"
      itemprop: "contentUrl"

  cafebiz:
    title:
      name: "h1"
      class_: "title"
    authors:
      class_: "detail-author"
    text:
      class_: "detail-content"
    pubd:
      class_: "timeandcatdetail"
    tags:
      class_: "tags"
    image_urls:
      name: "center"
      itemprop: "src"

  laodong:
    title:
      name: "h1"
    authors:
      name: "span"
      class_: "author"
    text:
      class_: "articleCon"
    pubd:
      name: "time"
      class_: "f-datetime"
    tags:
      name: "span"
      class_: "keywords"
    image_urls:
      name: "a"
